name: Org-wide Close Issues From Commit
on:
  push:
permissions:
  issues: write
  contents: read
jobs:
  close-issue-from-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues based on commit message
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywords = ['close', 'closes', 'closed', 'fix', 'fixes', 'fixed', 'resolve', 'resolves', 'resolved'];
            const issueRegex = new RegExp(`\\b(?:${keywords.join('|')})\\s+#(\\d+)`, 'gi');
            const commits = github.context.payload.commits;
            if (!commits) {
              return;
            }
            for (const commit of commits) {
              const matches = commit.message.matchAll(issueRegex);
              if (!matches) continue;
              for (const match of matches) {
                const issueNumber = parseInt(match[1], 10);
                if (isNaN(issueNumber)) continue;
                console.log(`Found keyword to close issue #${issueNumber} in commit ${commit.id.substring(0, 7)}.`);
                try {
                  await github.rest.issues.update({
                    owner: github.context.repo.owner,
                    repo: github.context.repo.repo,
                    issue_number: issueNumber,
                    state: 'closed'
                  });
                  const commentBody = `此問題已在提交 [${commit.id.substring(0, 7)}](${commit.url}) 中被自動關閉。`;
                  await github.rest.issues.createComment({
                    owner: github.context.repo.owner,
                    repo: github.context.repo.repo,
                    issue_number: issueNumber,
                    body: commentBody
                  });
                } catch (error) {
                  console.error(`Failed to close or comment on issue #${issueNumber}. Error: ${error.message}`);
                }
              }
            }
